### ISSUE TITLE
Events in input file caused mtv to crash

### ISSUE THREAD

**Issue by Fjolnirr** [nasa/trick#1469]
Hello,

I was trying to use an event for cannon_analytic project. However, There are 2 bugs that I have encountered;
1- After starting the simulation control panel I click on the mtv button but list of errors shows and mtv is not opening. (when I remove the event lines from input file mtv screen works normally)
2- I have set a condition where sim_time == 7.0 and as a result freeze the sim. When the sim hits the time of 7.10 it has frozen.
(Also tried it with sim_time > 7.0 and it freeze the sim at 8.10)

I was just implementing the event example shown here : https://nasa.github.io/trick/documentation/running_a_simulation/Input-File

Here is my event codes: (singleShotEvent.py which is executed inside of the input.py)
```
singleshot_event = trick.new_event("singleshot_event")
singleshot_event.condition(0, "trick.exec_get_sim_time() == 7.0")
singleshot_event.action(0, """
trick.freeze()
singleshot_event.activate()
""")
singleshot_event.activate()
trick.add_event(singleshot_event)
```
Here is the screenshot of my error:
![event_bug](https://user-images.githubusercontent.com/40665614/223349066-a27d6f89-b888-4ccd-aac7-5616b21e7b17.PNG)

Finally This is the error message that is shown:
```
|L   1|2023/03/07,09:58:34|ubuntuVm| |T 0|7.100000| Freeze ON. Simulation time holding at 7.100000 seconds.
Gtk-Message: 09:58:44.460: Failed to load module "canberra-gtk-module"
|L   3|2023/03/07,09:58:47|ubuntuVm| |T 0|7.100000| Variable Server could not find variable trick_ip.mtv.mtv_list[0][0].cond[0].comment.
|L   3|2023/03/07,09:58:47|ubuntuVm| |T 0|7.100000| Variable Server could not find variable trick_ip.mtv.mtv_list[0][0].act[0].comment.
VarClient: Unknown type 25 in get().
VarClient: Unknown type 25 in get().
Mar 07, 2023 9:58:47 AM org.jdesktop.application.Application$1 run
SEVERE: Application class trick.mtv.MtvApp failed to launch
java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6
        at trick.mtv.MtvApp.initialize(MtvApp.java:230)
        at org.jdesktop.application.Application$1.run(Application.java:186)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Exception in thread "AWT-EventQueue-0" java.lang.Error: Application class trick.mtv.MtvApp failed to launch
        at org.jdesktop.application.Application$1.run(Application.java:192)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6
        at trick.mtv.MtvApp.initialize(MtvApp.java:230)
        at org.jdesktop.application.Application$1.run(Application.java:186)
        ... 13 more
```

**Comment by Fjolnirr** [comment]
I have an update that when you add comments to the `.condition` and `.action` functions mtv opens. However, events doesnt listed in the mtv view. I think this is a bug because in the input file docs `"<optional comment displayed in mtv>"` this line added to those 2 functions.
