### ISSUE TITLE
Java Based Applications Throw java.awt.HeadlessException On Latest Ubuntu 24.04

### ISSUE THREAD

**Issue by rendayigit** [nasa/trick#1749]
I get the below error when I try to run applications such as `trick-tv` and `trick-simcontrol`. @Fjolnirr and I found a solution to this problem, we believe installing `openjdk-11-jdk` as mentioned in the [Install-Guide](https://nasa.github.io/trick/documentation/install_guide/Install-Guide#ubuntu) installs java as headless by default (on Ubuntu 24.04). Installing `default-jdk` by doing `apt-get install default-jdk` seems to solve this issue. So it may be a good idea to add this package to the [Install-Guide](https://nasa.github.io/trick/documentation/install_guide/Install-Guide#ubuntu).

``` bash
~/trick/bin/trick-tv
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
        at org.jdesktop.application.ResourceMap.<clinit>(ResourceMap.java:1354)
        at org.jdesktop.application.ResourceManager.createResourceMap(ResourceManager.java:468)
        at org.jdesktop.application.ResourceManager.createResourceMapChain(ResourceManager.java:151)
        at org.jdesktop.application.ResourceManager.createResourceMapChain(ResourceManager.java:150)
        at org.jdesktop.application.ResourceManager.createResourceMapChain(ResourceManager.java:150)
        at org.jdesktop.application.ResourceManager.getApplicationResourceMap(ResourceManager.java:170)
        at org.jdesktop.application.ResourceManager.getResourceMap(ResourceManager.java:307)
        at org.jdesktop.application.ApplicationContext.getResourceMap(ApplicationContext.java:206)
        at org.jdesktop.application.Application.create(Application.java:250)
        at org.jdesktop.application.Application$1.run(Application.java:185)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

        at java.desktop/sun.awt.HeadlessToolkit.getMenuShortcutKeyMask(HeadlessToolkit.java:135)
        at org.jdesktop.application.ResourceMap$KeyStrokeStringConverter.<clinit>(ResourceMap.java:1511)
        ... 23 more
```

**Comment by sharmeye** [comment]
Thanks, we'll look into this and update the install guide if necessary and credit you with the update

**Comment by hchen99** [comment]
@rendayigit @Fjolnirr thanks for the detailed helpful info. As a a matter of fact, the `java` (JRE) headless comes with ubuntu 24 by default (at least it's true for docker image since I don't have the access to an actual ubuntu 24 computer) not installed by `openjdk-11-jdk` pacakge. 

`openjdk-11-jdk` does set up `javac` & `java` properly. If you run `java -version`(21) and `javac -version` (11), you should see they are different if only installing `openjdk-11-jdk`. Ubuntu 24 docker container has `openjdk-11-jdk` installed in `/usr/lib/jvm/java-11-openjdk-amd64/`. So, if you set your PATH to find `/usr/lib/jvm/java-11-openjdk-amd64/bin` (where JRE 11 is in) before finding `/usr/bin` (where JRE 21 headless is in), installing `openjdk-11-jdk` works. 

Meanwhile, we're updating the install guide to use `default-jdk` package though as it does make it easier to keep `java` and `javac` versions consistent for ubuntu 24. Installing `default-jdk` works for other ubuntu versions as well.

Please feel free to let us know if you see things differently.
