### ISSUE TITLE
HDF5 data recording broken

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#188]
ARGOS records about 50 variables of various types at 5 kHz. We've been using DRAscii without issue, except that the resulting files are huge. Upon switching to HDF5, the sim segfaults 30 seconds into execution:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xf55feb70 (LWP 38707)]
0x00b955bf in H5FL_arr_malloc () from /usr/lib/libhdf5.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6_7.1.i686 hdf5-1.8.5.patch1-7.el6.i686 libgcc-4.4.7-16.el6.i686 libstdc++-4.4.7-16.el6.i686 python-libs-2.6.6-64.el6.i686 zlib-1.2.3-29.el6.i686
(gdb) where
#0  0x00b955bf in H5FL_arr_malloc () from /usr/lib/libhdf5.so.6
#1  0x00c9c483 in H5S_extent_copy () from /usr/lib/libhdf5.so.6
#2  0x00c9c74a in H5S_copy () from /usr/lib/libhdf5.so.6
#3  0x00b1fb1d in H5Dget_space () from /usr/lib/libhdf5.so.6
#4  0x00a8ff7b in H5TB_common_append_records () from /usr/lib/libhdf5_hl.so.6
#5  0x00a87ff7 in H5PTappend () from /usr/lib/libhdf5_hl.so.6
#6  0x0851171e in Trick::DRHDF5::format_specific_write_data (this=0x8dd0470, writer_offset=49292) at DRHDF5.cpp:228
#7  0x08516e38 in Trick::DataRecordGroup::write_data (this=0x8dd0470, must_write=true) at DataRecordGroup.cpp:602
#8  0x0851289b in Trick::DRDWriterThread::thread_body (this=0x8bf13a4) at DataRecordDispatcher.cpp:58
#9  0x0857f4e2 in Trick::ThreadBase::thread_helper (context=0x8bf13a4) at ThreadBase.cpp:328
#10 0x00731b69 in start_thread () from /lib/libpthread.so.0
#11 0x00674cce in clone () from /lib/libc.so.6
```

Sometimes, the HDF5 library emits errors (often with corrupted text) before crashing:
```
HDF5-DIAG: Error detected in HDF5 (1.8.5-patch1) thread 0:
  #000: ����./src/H5Dio.c line 266 in (): `���t write data
    major: Dataset
    minor: Write failed
  #4294967295: x���./src/H5Dio.c line 524 in ���write(): ����and dest data spaces have different sizes
    major: Invalid arguments to routine
    minor: Bad value
Segmentation fault
```

I was able to reproduce the issue with a simple test sim that records an array of 1000 doubles at 5 kHz. Although it never crashes, after a few minutes, it produces:
```
HDF5-DIAG: Error detected in HDF5 (1.8.5-patch1) thread 0:
  #000: ../../src/H5Dio.c line 266 in H5Dwrite(): can't write data
    major: Dataset
    minor: Write failed
  #001: ../../src/H5Dio.c line 578 in H5D_write(): can't write data
    major: Dataset
    minor: Write failed
  #002: ../../src/H5Dchunk.c line 1841 in H5D_chunk_write(): error looking up chunk address
    major: Dataset
    minor: Can't get value
  #003: ../../src/H5Dchunk.c line 2276 in H5D_chunk_get_info(): can't query chunk address
    major: Dataset
    minor: Can't get value
  #004: ../../src/H5Dbtree.c line 996 in H5D_btree_idx_get_addr(): can't get chunk info
    major: Dataset
    minor: Can't get value
  #005: ../../src/H5B.c line 330 in H5B_find(): unable to load B-tree node
    major: B-Tree node
    minor: Unable to protect metadata
  #006: ../../src/H5AC.c line 1597 in H5AC_protect(): H5C_protect() failed.
    major: Object cache
    minor: Unable to protect metadata
  #007: ../../src/H5C.c line 3333 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #008: ../../src/H5C.c line 8177 in H5C_load_entry(): unable to load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #009: ../../src/H5Bcache.c line 136 in H5B_load(): can't read B-tree node
    major: B-Tree node
    minor: Read failed
  #010: ../../src/H5Fio.c line 113 in H5F_block_read(): read from metadata accumulator failed
    major: Low-level I/O
    minor: Read failed
  #011: ../../src/H5Faccum.c line 152 in H5F_accum_read(): unable to allocate metadata accumulator buffer
    major: Virtual File Layer
    minor: Can't allocate space
  #012: ../../src/H5FL.c line 1110 in H5FL_blk_realloc(): memory allocation failed for block
    major: Resource unavailable
    minor: No space available for allocation
  #013: ../../src/H5FL.c line 888 in H5FL_blk_malloc(): memory allocation failed for chunk
    major: Resource unavailable
    minor: No space available for allocation
  #014: ../../src/H5FL.c line 208 in H5FL_malloc(): memory allocation failed for chunk
    major: Resource unavailable
    minor: No space available for allocation
```

**Comment by alexlin0** [comment]
I was able to get similar error messages using 1 variable at 5kHz in the ball sim running non-realtime.  It appears that at that rate we are overwhelming the HDF5 libraries ability to write out the data fast enough.
