### ISSUE TITLE
Mac java GUIs printing warning when starting.

### ISSUE THREAD

**Issue by alexlin0** [nasa/trick#607]
The sim_control panel and TV are some of the GUIs printing this message when they start.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jdesktop.application.utils.OSXAdapter (file:/Users/alex/trick/libexec/trick/java/lib/bsaf-1.9.2.jar) to constructor com.apple.eawt.Application()
WARNING: Please consider reporting this to the maintainers of org.jdesktop.application.utils.OSXAdapter
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Mac OS X Adapter could not talk to EAWT:
java.lang.NoSuchMethodException: com.apple.eawt.Application.addApplicationListener(com.apple.eawt.ApplicationListener)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2432)
	at org.jdesktop.application.utils.OSXAdapter.setHandler(OSXAdapter.java:143)
	at org.jdesktop.application.utils.OSXAdapter.setQuitHandler(OSXAdapter.java:74)
	at org.jdesktop.application.Application.create(Application.java:257)
	at org.jdesktop.application.Application$1.run(Application.java:185)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by alexlin0** [comment]
Ugh.  I duplicated this issue in #613.  My memory is going bad, I can't even remember adding issues just 2 weeks ago.  @spfennell likes the title of the more recent issue, I'm closing this one.
