### ISSUE TITLE
SIGSEGV/SIGSTOP during load checkpoint from simcontrol. Sierra and also centos 7. Tested on ball sim and cannon sim. 

### ISSUE THREAD

**Issue by spfennell** [nasa/trick#624]
`|L   1|2018/05/22,15:50:05|Scotts-MacBook-Pro.local| |T 0|0.000000| Finished loading checkpoint file.  Calling restart jobs.
restart message port = 51993
restart variable server message port = 51994
Process terminated by signal SIGSEGV
Attempting to generate stack trace... standby.
(lldb) process attach --pid 15324
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 98, in <module>
    import six
ImportError: No module named six
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Process 15324 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007fffb9ad0406 libsystem_kernel.dylib`__wait4_nocancel + 10
libsystem_kernel.dylib`__wait4_nocancel:
->  0x7fffb9ad0406 <+10>: jae    0x7fffb9ad0410            ; <+20>
    0x7fffb9ad0408 <+12>: movq   %rax, %rdi
    0x7fffb9ad040b <+15>: jmp    0x7fffb9ac8caf            ; cerror_nocancel
    0x7fffb9ad0410 <+20>: retq   
Target 0: (S_main_Darwin_16.exe) stopped.

Executable module set to "/Users/sfennell/trick/trick_sims/Ball/SIM_ball_L1/./S_main_Darwin_16.exe".
Architecture set to: x86_64h-apple-macosx.
(lldb) command source -s 0 '/Users/sfennell/trick/share/trick/lldb_commands'
Executing commands in '/Users/sfennell/trick/share/trick/lldb_commands'.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007fffb9ad0406 libsystem_kernel.dylib`__wait4_nocancel + 10
    frame #1: 0x00007fffb9a56e3d libsystem_c.dylib`system + 463
    frame #2: 0x000000010f580d32 S_main_Darwin_16.exe`Trick::Executive::signal_handler(int) + 1394
    frame #3: 0x000000010f5865ca S_main_Darwin_16.exe`sig_hand(int) + 42
    frame #4: 0x00007fffb9bb0b3a libsystem_platform.dylib`_sigtramp + 26
    frame #5: 0x000000010f757b8f S_main_Darwin_16.exe`DLL_GetHeadPosition + 79
    frame #6: 0x000000010fb7f0f3 S_main_Darwin_16.exe`ref_free + 51
    frame #7: 0x000000010f535f95 S_main_Darwin_16.exe`Trick::DataRecordBuffer::~DataRecordBuffer() + 149
    frame #8: 0x000000010f535ff5 S_main_Darwin_16.exe`Trick::DataRecordBuffer::~DataRecordBuffer() + 21
    frame #9: 0x000000010f539dbd S_main_Darwin_16.exe`Trick::DataRecordGroup::remove_all_variables() + 573
    frame #10: 0x000000010f541b6f S_main_Darwin_16.exe`Trick::DataRecordGroup::shutdown() + 111
    frame #11: 0x000000010f53380d S_main_Darwin_16.exe`Trick::DataRecordDispatcher::remove_group(Trick::DataRecordGroup*) + 2029
    frame #12: 0x000000010f542dd0 S_main_Darwin_16.exe`remove_data_record_group + 48
    frame #13: 0x000000010f58d83d S_main_Darwin_16.exe`Trick::FrameLog::remove_recording_groups_from_sim() + 429
    frame #14: 0x000000010f58f355 S_main_Darwin_16.exe`Trick::FrameLog::clear_data_record_info() + 37
    frame #15: 0x000000010f3d43f2 S_main_Darwin_16.exe`FrameLogSimObject::call_function(Trick::JobData*) + 226
    frame #16: 0x000000010f64208a S_main_Darwin_16.exe`Trick::JobData::call() + 170
    frame #17: 0x000000010f52064a S_main_Darwin_16.exe`Trick::CheckPointRestart::load_checkpoint_job() + 1466
    frame #18: 0x000000010f3d2591 S_main_Darwin_16.exe`CheckPointRestartSimObject::call_function(Trick::JobData*) + 417
    frame #19: 0x000000010f64208a S_main_Darwin_16.exe`Trick::JobData::call() + 170
    frame #20: 0x000000010f56e3da S_main_Darwin_16.exe`Trick::Executive::freeze_loop() + 1034
    frame #21: 0x000000010f574a9c S_main_Darwin_16.exe`Trick::Executive::loop_single_thread() + 140
    frame #22: 0x000000010f572d0f S_main_Darwin_16.exe`Trick::Executive::loop() + 175
    frame #23: 0x000000010f754f48 S_main_Darwin_16.exe`master(int, char**) + 184
    frame #24: 0x000000010f3e1992 S_main_Darwin_16.exe`main + 34
    frame #25: 0x00007fffb99a1235 libdyld.dylib`start + 1
(lldb) quit
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'lldb' is not defined`

**Comment by spfennell** [comment]
From centos 7: 
```
Process terminated by signal SIGSEGV
[New LWP 3678]
[New LWP 3673]
[New LWP 3630]
[New LWP 3626]
[New LWP 3625]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007f5992ba81c9 in waitpid () from /lib64/libc.so.6

Thread 6 (Thread 0x7f59887f2700 (LWP 3625)):
#0  0x00007f5992bd8c73 in select () from /lib64/libc.so.6
#1  0x000000000068812f in Trick::VariableServerListenThread::thread_body() ()
#2  0x0000000000681cd5 in Trick::ThreadBase::thread_helper(void*) ()
#3  0x00007f5994d93e25 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f5992be1bad in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7f5987ff1700 (LWP 3626)):
#0  0x00007f5992bd8c73 in select () from /lib64/libc.so.6
#1  0x0000000000661959 in Trick::MessageTCDeviceListenThread::thread_body() ()
#2  0x0000000000681cd5 in Trick::ThreadBase::thread_helper(void*) ()
#3  0x00007f5994d93e25 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f5992be1bad in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7f59875dd700 (LWP 3630)):
#0  0x00007f5994d97995 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000617ac4 in Trick::DRDWriterThread::thread_body() ()
#2  0x0000000000681cd5 in Trick::ThreadBase::thread_helper(void*) ()
#3  0x00007f5994d93e25 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f5992be1bad in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7f598555c700 (LWP 3673)):
#0  0x00007f5992ba856d in nanosleep () from /lib64/libc.so.6
#1  0x00007f5992bd9404 in usleep () from /lib64/libc.so.6
#2  0x000000000068ec92 in Trick::VariableServerThread::thread_body() ()
#3  0x0000000000681cd5 in Trick::ThreadBase::thread_helper(void*) ()
#4  0x00007f5994d93e25 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f5992be1bad in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f5984d5b700 (LWP 3678)):
#0  0x00007f5992ba856d in nanosleep () from /lib64/libc.so.6
#1  0x00007f5992bd9404 in usleep () from /lib64/libc.so.6
#2  0x000000000068ec92 in Trick::VariableServerThread::thread_body() ()
#3  0x0000000000681cd5 in Trick::ThreadBase::thread_helper(void*) ()
#4  0x00007f5994d93e25 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f5992be1bad in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f5995573740 (LWP 3624)):
#0  0x00007f5992ba81c9 in waitpid () from /lib64/libc.so.6
#1  0x00007f5992b25e52 in do_system () from /lib64/libc.so.6
#2  0x00007f5992b26201 in system () from /lib64/libc.so.6
#3  0x0000000000639915 in Trick::Executive::signal_handler(int) ()
#4  0x000000000063ab5c in sig_hand(int) ()
#5  <signal handler called>
#6  0x00007f5992b68c3c in free () from /lib64/libc.so.6
#7  0x0000000000619cb9 in Trick::DataRecordBuffer::~DataRecordBuffer() ()
#8  0x000000000061ac2f in Trick::DataRecordGroup::remove_all_variables() ()
#9  0x000000000061c723 in Trick::DataRecordGroup::shutdown() ()
#10 0x0000000000618178 in Trick::DataRecordDispatcher::remove_group(Trick::DataRecordGroup*) ()
#11 0x000000000061e07f in remove_data_record_group ()
#12 0x000000000063ebed in Trick::FrameLog::remove_recording_groups_from_sim() ()
#13 0x000000000063f7fe in Trick::FrameLog::clear_data_record_info() ()
#14 0x000000000057a349 in FrameLogSimObject::call_function (this=0xe59000 <trick_frame_log>, curr_job=0x245bf40) at build/S_source.cpp:735
#15 0x000000000067effd in Trick::JobData::call() ()
#16 0x0000000000612aab in Trick::CheckPointRestart::load_checkpoint_job() ()
#17 0x00000000005794f8 in CheckPointRestartSimObject::call_function (this=0xe57360 <trick_cpr>, curr_job=0x22bebb0) at build/S_source.cpp:193
#18 0x000000000067effd in Trick::JobData::call() ()
#19 0x000000000062f4a1 in Trick::Executive::freeze_loop() ()
#20 0x0000000000632584 in Trick::Executive::loop_single_thread() ()
#21 0x000000000063240e in Trick::Executive::loop() ()
#22 0x00000000006fa4bc in master(int, char**) ()
#23 0x000000000057e5d5 in main (nargs=2, args=0x7ffd03b4bda8) at build/S_source.cpp:1388
```
