### ISSUE TITLE
importing yaml in the input file causes SIGFPE

### ISSUE THREAD

**Issue by dbankieris** [nasa/trick#890]
Only happens when `trick.exec_set_trap_sigfpe` is `True`. Haven't found any otrher modules for which this occurs. No idea what's going on.

```python
trick.exec_set_trap_sigfpe(True)
import yaml
```

```
Program received signal SIGFPE, Arithmetic exception.
0x00007ffff7a7c605 in float_mul () from /lib64/libpython2.7.so.1.0
(gdb) where
#0  0x00007ffff7a7c605 in float_mul () from /lib64/libpython2.7.so.1.0
#1  0x00007ffff7a569ac in binary_op1 () from /lib64/libpython2.7.so.1.0
#2  0x00007ffff7a58dca in PyNumber_Multiply () from /lib64/libpython2.7.so.1.0
#3  0x00007ffff7af0480 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#4  0x00007ffff7af608d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#5  0x00007ffff7af358c in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#6  0x00007ffff7af608d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#7  0x00007ffff7af6192 in PyEval_EvalCode () from /lib64/libpython2.7.so.1.0
#8  0x00007ffff7b05f7c in PyImport_ExecCodeModuleEx () from /lib64/libpython2.7.so.1.0
#9  0x00007ffff7b061f8 in load_source_module () from /lib64/libpython2.7.so.1.0
#10 0x00007ffff7b06e91 in import_submodule () from /lib64/libpython2.7.so.1.0
#11 0x00007ffff7b070dd in load_next () from /lib64/libpython2.7.so.1.0
#12 0x00007ffff7b07abe in PyImport_ImportModuleLevel () from /lib64/libpython2.7.so.1.0
#13 0x00007ffff7aead6f in builtin___import__ () from /lib64/libpython2.7.so.1.0
#14 0x00007ffff7a5aab3 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#15 0x00007ffff7aec947 in PyEval_CallObjectWithKeywords () from /lib64/libpython2.7.so.1.0
#16 0x00007ffff7af1605 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#17 0x00007ffff7af608d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#18 0x00007ffff7af6192 in PyEval_EvalCode () from /lib64/libpython2.7.so.1.0
#19 0x00007ffff7b05f7c in PyImport_ExecCodeModuleEx () from /lib64/libpython2.7.so.1.0
#20 0x00007ffff7b061f8 in load_source_module () from /lib64/libpython2.7.so.1.0
#21 0x00007ffff7b06e91 in import_submodule () from /lib64/libpython2.7.so.1.0
#22 0x00007ffff7b070dd in load_next () from /lib64/libpython2.7.so.1.0
#23 0x00007ffff7b07abe in PyImport_ImportModuleLevel () from /lib64/libpython2.7.so.1.0
#24 0x00007ffff7aead6f in builtin___import__ () from /lib64/libpython2.7.so.1.0
#25 0x00007ffff7a5aab3 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#26 0x00007ffff7aec947 in PyEval_CallObjectWithKeywords () from /lib64/libpython2.7.so.1.0
#27 0x00007ffff7af1605 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#28 0x00007ffff7af608d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#29 0x00007ffff7af6192 in PyEval_EvalCode () from /lib64/libpython2.7.so.1.0
#30 0x00007ffff7b05f7c in PyImport_ExecCodeModuleEx () from /lib64/libpython2.7.so.1.0
#31 0x00007ffff7b061f8 in load_source_module () from /lib64/libpython2.7.so.1.0
#32 0x00007ffff7b0768a in load_package () from /lib64/libpython2.7.so.1.0
#33 0x00007ffff7b06e91 in import_submodule () from /lib64/libpython2.7.so.1.0
#34 0x00007ffff7b070dd in load_next () from /lib64/libpython2.7.so.1.0
#35 0x00007ffff7b07abe in PyImport_ImportModuleLevel () from /lib64/libpython2.7.so.1.0
#36 0x00007ffff7aead6f in builtin___import__ () from /lib64/libpython2.7.so.1.0
#37 0x00007ffff7a5aab3 in PyObject_Call () from /lib64/libpython2.7.so.1.0
#38 0x00007ffff7aec947 in PyEval_CallObjectWithKeywords () from /lib64/libpython2.7.so.1.0
#39 0x00007ffff7af1605 in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#40 0x00007ffff7af370d in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#41 0x00007ffff7af608d in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#42 0x00007ffff7af6192 in PyEval_EvalCode () from /lib64/libpython2.7.so.1.0
#43 0x00007ffff7b0f5cf in run_mod () from /lib64/libpython2.7.so.1.0
#44 0x00007ffff7b1079e in PyRun_FileExFlags () from /lib64/libpython2.7.so.1.0
#45 0x00007ffff7b11a29 in PyRun_SimpleFileExFlags () from /lib64/libpython2.7.so.1.0
#46 0x0000000000750887 in Trick::IPPython::init (this=0xf119c0 <trick_ip+96>) at IPPython.cpp:138
#47 0x00000000005a16d4 in InputProcessorSimObject::call_function (this=0xf11960 <trick_ip>, 
    curr_job=0x10bc1f0) at build/S_source.cpp:387
#48 0x00000000006bf743 in Trick::JobData::call (this=0x10bc1f0) at JobData.cpp:182
#49 0x00000000006692b4 in Trick::Executive::call_input_processor (this=0xf100c0 <trick_sys+96>)
    at Executive_call_input_processor.cpp:30
#50 0x000000000066e4de in Trick::Executive::init (this=0xf100c0 <trick_sys+96>) at Executive_init.cpp:41
#51 0x0000000000748c3a in master (nargs=2, args=0x7fffffffda08) at master.cpp:42
#52 0x00000000005a662f in main (nargs=2, args=0x7fffffffda08) at build/S_source.cpp:1447
```

**Comment by DavidHammen** [comment]
I saw very similar behavior (including a very deep call stack) when importing pandas and calling pandas.HDFStore after getting around issue #909 by temporarily resetting the SIGCHLD handler to SIG_DFL.

I do not see this behavior with yaml. My machine has python 2.7.15+ and yaml 3.12.
